version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis-server
    ports:
      - "6379:6379"

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    ports:
      - "8080:8080" # UI do Spark Master
      - "7077:7077" # Porta RPC do Spark Master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
      - SPARK_LOG_DIR=/opt/bitnami/spark/logs
      - IVY_HOME=/tmp/.ivy2

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
      - redis
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
      - SPARK_LOG_DIR=/opt/bitnami/spark/logs
      - IVY_HOME=/tmp/.ivy2

  spark-app:
    build: .
    container_name: spark-app
    depends_on:
      - spark-master
      - redis
    ports:
      - "5000:5000" # Porta do Flask
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HOME=/tmp
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

  # Serviço de Monitoramento de Listas Redis
  redis-list-monitor:
    build:
      context: ./redis_monitor
      dockerfile: Dockerfile_Monitor
    container_name: redis-list-monitor
    depends_on:
      - redis
      - spark-app
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      SPARK_APP_URL: http://spark-app:5000/trigger-spark-job
      MONITOR_INTERVAL_SECONDS: 10
      LIST_THRESHOLDS_JSON: |
          {"raw_travel_data_list": 50, "raw_flights": 50}

volumes:
  spark_master_data:
  spark_master_logs:
  spark_worker_data:
  spark_worker_logs: