services:
  redis-server:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    networks:
      - a2_comp_escalavel_default

  spark-master:
    image: bitnami/spark:3.5.1
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master internal communication
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - a2_comp_escalavel_default

  # Serviço para gerar dados fixos (executa uma vez e para)
  data-generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    environment:
      S3_PREFIX_HOTEIS: master_data/hoteis/
      S3_PREFIX_VOOS: master_data/voos/
      PG_DATA_HOST: a2-comp-escalavel-dados-fixos.col2wfyf2csx.us-east-1.rds.amazonaws.com
      PG_DATA_PORT: 5432
      PG_DATA_DB: postgres
      PG_DATA_USER: A2CompEscalavel
      PG_DATA_PASSWORD: euadoroaemap
      AWS_DEFAULT_REGION: us-east-1
    networks:
      - a2_comp_escalavel_default
    restart: "no"

  spark-worker:
    image: bitnami/spark:3.5.1
    depends_on:
      - spark-master
      - redis-server
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_MODE=worker
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - a2_comp_escalavel_default

  # Serviço para o job Spark
  spark-batch-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      spark-master:
        condition: service_started
      redis-server:
        condition: service_started
      data-generator:
        condition: service_completed_successfully
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      MONITOR_INTERVAL_SECONDS: 10
      LIST_THRESHOLDS_JSON: |
        {"raw_hotels": 50, "raw_flights": 50}
      PG_DATA_HOST: a2-comp-escalavel-dados-gerais.col2wfyf2csx.us-east-1.rds.amazonaws.com
      PG_DATA_PORT: 5432
      PG_DATA_DB: dados_gerais
      PG_DATA_USER: emap
      PG_DATA_PASSWORD: emap123
      # PostgreSQL Estatísticas
      PG_STATS_HOST: postgres-stats
      PG_STATS_PORT: 5432
      PG_STATS_DB: dados_stats
      PG_STATS_USER: emap
      PG_STATS_PASSWORD: emap123
      S3_MASTER_DATA_BUCKET: a2-comp-escalavel-dados-brutos
      S3_PREFIX_HOTEIS: master_data/hoteis/
      S3_PREFIX_VOOS: master_data/voos/
      AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
      AWS_SESSION_TOKEN: <AWS_SESSION_TOKEN>
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: ["/opt/bitnami/python/bin/python", "main.py"]
    networks:
      - a2_comp_escalavel_default

networks:
  a2_comp_escalavel_default: