[project]
name = "a2-comp-escalavel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyspark>=4.0.0",
    "redis>=5.0.0",
    "Flask>=2.0.0",
    "requests>=2.0.0",
    "faker>=37.4.0",
]
